[pytest]
norecursedirs = openTask .git .gitignore *.egg-info build dist .tox __pycache__ .pytest_cache .mypy_cache .hypothesis
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
asyncio_mode = auto